server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  mustache:
    suffix:.hbs
  datasource:
    url: jdbc:postgresql://dev-crawling-db.gelato.im:5432/instagram_crawling_db
    username: gelato
    password: wpffkEh16)&
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    url: jdbc:postgresql://dev-crawling-db.gelato.im:5432/instagram_crawling_db
    enabled: true
    encoding: UTF-8
    user: gelato
    password: wpffkEh16)&
    baseline-on-migrate: true